name: Deploy

on:
  push:
    branches: [ feat-cd ]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: caching deps
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ github.sha }}

  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: caching deps
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ github.sha }}

  publish:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: restore deps
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ github.sha }}
    - run: yarn build
    - run: yarn lerna link
    - run: yarn lerna changed
    - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - name: publish
      run: env && npm whoami
      env:
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: rm .npmrc
